service: linebot

provider:
  name: aws
  region: ap-northeast-1  
  runtime: nodejs6.10
  vpc:
    securityGroupIds:
     - "sg-db38a1a2"
    subnetIds:
     - "subnet-44e59e0d"
functions:
  line:
    handler: handler.line
    events:
      - http:
          method: post
          path: line
    vpc:
      securityGroupIds:
      - "sg-db38a1a2"
      subnetIds:
      - "subnet-44e59e0d"
plugins:
  - serverless-webpack
  - serverless-offline